spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/cms?serverTimezone=GMT%2B8&useSSL=true&useUnicode=true&characterEncoding=UTF8
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:oracle:thin:@192.168.0.241:1521:ora11g
      username: root
      password: 123456

      # 初始化大小，最小，最大
      initialSize: 3
      minIdle: 3
      maxActive: 10
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1
      testWhileIdle: false
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
  cache:
      type: ehcache
      ehcache:
          config: config/ehcache.xml
  redis:
      host: @cache.redis.host@
      port: @cache.redis.port@
      #连接超时时间（毫秒）
      timeout: 10000
      pool:
      #连接池中的最大空闲连接
      max-idle: 8
      #连接池中的最小空闲连接
      min-idle: 10
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      password:
mybatis:
#    configuration:
#        map-underscore-to-camel-case: true
    #mapper.xml所在位置
    mapper-locations: mybatis/**/*Mapper.xml
    #实体类所做包
    type-aliases-package: com.yaa.cms.*.model
